spring:
  application:
    name: Spring_Sem04
sql:
  sqlFindAll: "SELECT * FROM userTable"
  sqlSave: "INSERT INTO userTable (firstName, lastName) VALUES (?, ?)"
  sqlDeleteById: "DELETE FROM userTable WHERE id=?"
  sqlUpdateUser: "UPDATE userTable SET firstName = ?, lastName = ? WHERE id = ?"
  sqlGetOne: "SELECT * FROM userTable WHERE id = "
